version: '3.3'

services:
  node-app:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    image: boilerplate-node-fsvc
    env_file: ./.env
    ports:
      - 3000:$PORT
    volumes:
      - ./:/usr/src/node-app
    stdin_open: true
    tty: true